# Generated by Django 4.1.3 on 2022-12-07 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='describers', to=settings.AUTH_USER_MODEL)),
                ('describer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed', through='users.Subscriber', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.CheckConstraint(check=models.Q(('author', models.F('describer'))), name='impossible_follow_self'),
        ),
    ]
